### ISSUE TITLE
Can't perform the dark prayer

### ISSUE THREAD

**Issue by Faye-Rhayne** [Team-Eidolon/eidolon#23]
We have the Wicked Sign unlocked, altar built w/ effigy, and decorated, but when we go click on the Wicked symbol, it just takes us to the info page, instead of selecting the symbol x3 to perform the dark prayer.

**Comment by QinomeD** [comment]
You need runes, they are currently only obtainable through commands

**Comment by Wakatsu** [comment]
So what command unlocks runes? Also why change the system at all?

**Comment by QinomeD** [comment]
Use the /knowledge command.

System is different, because Elucent changed it while working on the official 1.18.1 port, which is discontinued.
