### ISSUE TITLE
Eidolon Guide Book Crash

### ISSUE THREAD

**Issue by Sheeps44** [Team-Eidolon/eidolon#31]
Getting this error when opening certain pages on the guide book:

"Description: Rendering screen
java.lang.IllegalStateException: Not building!"

It causes a crash right after I try to open the page, I'm assuming its having some issue with rendering the page.

[crash-2023-10-10_00.19.56-client.txt](https://github.com/Team-Eidolon/eidolon/files/12853995/crash-2023-10-10_00.19.56-client.txt)

**Comment by QinomeD** [comment]
Eidolon is currently incompatible with Immediately Fast
